services:
  - type: web
    name: air-quality-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bokeh serve --address=0.0.0.0 --port=$PORT aqi_dash.py --allow-websocket-origin=*